### PR TITLE
Change Cues namespace to match specification

### PR DESCRIPTION
**Pull request by twagoo**
Fix for #14

Also including a number of small other pending improvements.

### CODE REVIEW

**Review by menzowindhouwer — APPROVED** [review]
cmd-component-1_2-to-1_1.xsl is robust, i.e. can handle the wrong and right cue namespace, should we do the same for comp2schema.xsl? These are the 2 stylesheets used by the CR, but do they need to be this robust ... on the other hand only small changes are needed to make them thus.

The schematron files contain at the top commented out rules, which can just be deleted.

**Comment by twagoo** [comment]
> cmd-component-1_2-to-1_1.xsl is robust, i.e. can handle the wrong and right cue namespace, should we do the same for comp2schema.xsl? These are the 2 stylesheets used by the CR, but do they need to be this robust ... on the other hand only small changes are needed to make them thus.

Yes well spotted and good idea. Somehow I like the idea of being able to transform all CMDI 1.2.x components and profiles with the toolkit, even if the component registry _should_ be internally consistent. I'll propose a change for `comp2schema.xsl`.

> The schematron files contain at the top commented out rules, which can just be deleted.

I will do that 👍

**Comment by twagoo** [comment]
> > cmd-component-1_2-to-1_1.xsl is robust, i.e. can handle the wrong and right cue namespace, should we do the same for comp2schema.xsl?
>
> (..)
>
> > The schematron files contain at the top commented out rules, which can just be deleted.


@menzowindhouwer I have implemented your two suggestions in cba74512682b...a4991c157

**Review by menzowindhouwer — APPROVED** [review]
Looks and runs fine :-)

**Pull request merged**
